# Generated by Django 5.1.1 on 2025-02-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FakultetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fakultet', models.CharField(max_length=100)),
                ('students', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Number of students Data',
            },
        ),
    ]
